services:
  - type: web
    name: bloghub
    env: php
    plan: free
    buildCommand: composer install --no-dev --optimize-autoloader && php artisan config:cache && php artisan route:cache && php artisan view:cache
    startCommand: php -S 0.0.0.0:$PORT -t public
    envVars:
      - key: APP_NAME
        value: BlogHub
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:vynOWXh2AfUZcThaPcEREqGvY0YThDP6RHiTtuHH8Zk=
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: aws-1-eu-west-1.pooler.supabase.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres.vjsufrnecikghptpwpbv
      - key: DB_PASSWORD
        value: BlogHub@2024!
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_STORE
        value: array